url = https://demoqa.com/automation-practice-form
firstNameId = firstName
lastNameCss = input[placeholder="Last Name"]
emailXpath = /html/body/div[2]/div/div/div/div[2]/div[2]/form/div[2]/div[2]/input